import React from 'react';
import { motion } from 'motion/react';
import { ArrowUpRight, Check, MessageCircle, MoveUpRight, Box, Cloud, Code2, Link2, ServerCog, Smartphone } from 'lucide-react';
import { TEAM } from '../site';
import alexPhoto from '../../project images/Alex.jpg';
import nakashimaPhoto from '../../project images/Nakashima.jpg';
import oleksandrPhoto from '../../project images/Oleksandr.jpg';
import evermergeImage from '../../project images/EverMerge.jpg';
import musicRacingImage from '../../project images/Music Racing.jpg';
import dragaliaImage from '../../project images/Dragalia Lost.jpg';
import rollbitImage from '../../project images/rollbit.jpg';
import rajampoImage from '../../project images/rajampo.jpg';
import sodashiImage from '../../project images/SODASHI.jpg';
import dividendImage from '../../project images/DIVIDEND.jpg';
import needsBankImage from '../../project images/NeedsBank.jpg';
import doctoreImage from '../../project images/Lotus car.jpg';
import chatImage from '../../project images/chatswap.jpg';
import webDevImage from '../assets/images/service_web_dev_1785678035261.jpg';
import webDevImageWebp from '../assets/images/service_web_dev_1785678035261.webp';
import interactiveImage from '../assets/images/service_motion_3d_1785678083789.jpg';
import interactiveImageWebp from '../assets/images/service_motion_3d_1785678083789.webp';
import identityImage from '../assets/images/service_visual_identity_1785678066566.jpg';
import identityImageWebp from '../assets/images/service_visual_identity_1785678066566.webp';
import strategyImage from '../assets/images/service_brand_strategy_1785678050686.jpg';
import strategyImageWebp from '../assets/images/service_brand_strategy_1785678050686.webp';

const services = [
  { number: '01', title: 'Product engineering', eyebrow: 'BUILD / SCALE', body: 'End-to-end web platforms and applications built to last.', detail: 'From product architecture to polished frontend systems, we make complex digital products feel simple to use and dependable to run.', stack: 'React  Â·  Next.js  Â·  TypeScript  Â·  Node.js', image: webDevImage, webp: webDevImageWebp },
  { number: '02', title: 'Interactive development', eyebrow: 'MOVE / ENGAGE', body: 'WebGL, Unity, and real-time experiences with a reason to exist.', detail: 'Motion, depth, and real-time interaction shaped around the story your product needs to tell.', stack: 'WebGL  Â·  Three.js  Â·  Unity  Â·  C#', image: interactiveImage, webp: interactiveImageWebp },
  { number: '03', title: 'Blockchain systems', eyebrow: 'CONNECT / TRUST', body: 'Practical decentralized products, integrations, and smart-contract work.', detail: 'Wallet flows, Web3 products, and smart-contract integrations that make new technology feel approachable.', stack: 'Solidity  Â·  Web3  Â·  React  Â·  Node.js', image: identityImage, webp: identityImageWebp },
  { number: '04', title: 'Cloud & delivery', eyebrow: 'SHIP / EVOLVE', body: 'Infrastructure, release confidence, and reliable operational foundations.', detail: 'Cloud architecture, deployment workflows, and performance work that keep your team moving after launch.', stack: 'AWS  Â·  Azure  Â·  Docker  Â·  Firebase', image: strategyImage, webp: strategyImageWebp },
];

const technologies = [
  { label: 'Interface', items: ['React', 'Next.js', 'TypeScript', 'Vue', 'WebGL'] },
  { label: 'Systems', items: ['Node.js', 'Python', 'Laravel', 'Django', 'Go', 'Java'] },
  { label: 'Cloud', items: ['AWS', 'Azure', 'Firebase', 'Docker', 'MongoDB', 'MySQL'] },
  { label: 'Immersive', items: ['Unity', 'Unreal Engine', 'C#', 'C++', 'Blender', 'Maya'] },
  { label: 'Web3', items: ['Solidity', 'Web3', 'Rust'] },
  { label: 'Mobile', items: ['React Native'] },
];

const technologyIcons = { Interface: Code2, Systems: ServerCog, Cloud, Immersive: Box, Web3: Link2, Mobile: Smartphone };

const projects = [
  { title: 'EverMerge', category: 'Mobile game', stack: ['Unity', 'C#'], image: evermergeImage, text: 'A polished puzzle-world experience made for long sessions and playful discovery.' },
  { title: 'Music Racing GT', category: 'Racing game', stack: ['Unity', 'C#'], image: musicRacingImage, text: 'Rhythm-led racing with a high-energy visual identity and responsive play.' },
  { title: 'Dragalia Lost', category: 'Mobile game', stack: ['Unity', 'C#'], image: dragaliaImage, text: 'Character-driven action for a vibrant, expansive fantasy world.' },
  { title: 'RollBit', category: 'Web3 platform', stack: ['React', 'Web3'], image: rollbitImage, text: 'A sharp, fast digital product experience for a high-traffic platform.' },
  { title: 'Rajampo', category: 'Digital product', stack: ['React', 'Node.js'], image: rajampoImage, text: 'A focused product interface with a distinct visual point of view.' },
  { title: 'Sodashi', category: 'Commerce', stack: ['React', 'Next.js'], image: sodashiImage, text: 'A refined commerce presentation with an editorial sense of pace.' },
  { title: 'Dividend Finance', category: 'Fintech', stack: ['React', 'AWS'], image: dividendImage, text: 'Clear digital infrastructure for a finance-led customer journey.' },
  { title: 'Needs Bank', category: 'Fintech', stack: ['React', 'Node.js'], image: needsBankImage, text: 'An approachable banking interface designed around clarity and trust.' },
  { title: 'Doctore', category: 'Health platform', stack: ['React', 'Cloud'], image: doctoreImage, text: 'A considered service experience for people navigating care.' },
  { title: 'Chat / Live Streaming Platform', category: 'Social platform', stack: ['React', 'WebRTC'], image: chatImage, text: 'Real-time conversation and live connection in one fluid platform.' },
];

const process = [
  ['01', 'Frame the opportunity', 'We get precise about the goal, the audience, and the constraints before making promises.'],
  ['02', 'Make the plan visible', 'Scope, priorities, and milestones are clear enough for every stakeholder to follow.'],
  ['03', 'Build in focused cycles', 'Senior hands stay close to the work, turning decisions into tested product increments.'],
  ['04', 'Ship with confidence', 'Quality checks, release coordination, and handover keep the final stretch calm.'],
  ['05', 'Stay useful after launch', 'We remain available for the measured improvements that keep a product moving.'],
];

const ease = [0.16, 1, 0.3, 1] as const;
const Reveal = ({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) => (
  <motion.div className={className} initial={{ opacity: 0, y: 24, filter: 'blur(5px)' }} whileInView={{ opacity: 1, y: 0, filter: 'blur(0px)' }} viewport={{ once: true, margin: '0px 0px -60px 0px', amount: .1 }} transition={{ duration: .8, delay, ease }}>{children}</motion.div>
);

function PageLead({ index, kicker, title, intro }: { index: string; kicker: string; title: string; intro: string }) {
  return <section className="bg-[#F2F2F2] px-6 pb-16 pt-16 sm:px-10 sm:pb-24 sm:pt-24 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/55"><span>{index}</span><span>{kicker}</span></div><Reveal><h1 className="mt-10 max-w-5xl text-[clamp(3.1rem,8vw,7.7rem)] font-medium leading-[.84] tracking-[-.075em] text-black">{title}</h1></Reveal><Reveal delay={.1}><p className="mt-10 max-w-xl text-base leading-7 text-black/65 sm:text-lg">{intro}</p></Reveal></div></section>;
}

function ContactBand({ compact = false }: { compact?: boolean }) {
  return <section className={`bg-[#F2F2F2] px-6 lg:px-14 ${compact ? 'py-8 sm:py-12' : 'py-16 sm:py-20'}`}><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 border-t border-black/15 pt-4 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/50">START A CONVERSATION</p><h2 className={`mt-4 max-w-2xl font-medium leading-[.94] tracking-[-.055em] ${compact ? 'text-4xl sm:text-5xl' : 'text-5xl sm:text-6xl'}`}>A clear brief is a good place to begin.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><a href="mailto:saasbusiness2026@gmail.com" className="group inline-flex items-center justify-between gap-8 bg-black px-5 py-4 font-mono text-xs font-bold tracking-wide text-white transition-transform duration-300 hover:-translate-y-1"><span>EMAIL NDA</span><ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></a><a href="https://wa.me/380937713309" target="_blank" rel="noreferrer" className="group inline-flex items-center justify-between gap-8 border border-black/20 bg-white px-5 py-4 font-mono text-xs font-bold tracking-wide transition-colors hover:border-black"><span>WHATSAPP</span><MessageCircle size={16} /></a></div></div></section>;
}

export function AboutPage() { return <><PageLead index="01" kicker="ABOUT NDA" title="A senior team for work that needs to hold up." intro="NDA brings engineering, immersive technology, and steady delivery management together. We work closely, communicate plainly, and take ownership of the details that matter." /><section className="bg-black px-6 py-16 text-white sm:px-10 sm:py-24 lg:px-14"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1fr_1.5fr]"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">WHAT GUIDES US</p><h2 className="mt-6 text-4xl leading-[.95] tracking-[-.045em] sm:text-5xl">Quietly rigorous. Genuinely collaborative.</h2></Reveal><div className="grid gap-x-10 gap-y-12 sm:grid-cols-2">{[['Senior ownership', 'The people shaping the work are the people accountable for delivering it.'], ['Useful ambition', 'We enjoy difficult problems, but never add complexity for its own sake.'], ['Visible progress', 'Decisions, priorities, and progress stay easy to understand.'], ['Long-term thinking', 'We build foundations that are ready for the work after launch.']].map(([title, body], i) => <Reveal key={title} delay={i * .06} className="border-t border-white/20 pt-4"><p className="font-mono text-xs font-bold">{title}</p><p className="mt-4 max-w-xs text-sm leading-6 text-white/60">{body}</p></Reveal>)}</div></div></section><section className="bg-[#F2F2F2] px-6 py-16 sm:px-10 sm:py-24 lg:px-14"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-12"><Reveal className="md:col-span-4"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/50">HOW WE SHOW UP</p></Reveal><div className="md:col-span-8"><Reveal><p className="max-w-3xl text-3xl leading-tight tracking-[-.045em] sm:text-5xl">One team, close to the workâ€”from the first practical question to the release that follows it.</p></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-3">{['Set direction', 'Design the route', 'Deliver deliberately'].map((item, i) => <Reveal key={item} delay={i * .07} className="border-t border-black/15 pt-4"><span className="font-mono text-xs text-black/45">0{i + 1}</span><p className="mt-9 text-xl tracking-tight">{item}</p></Reveal>)}</div></div></div></section><ContactBand compact /></> }

export function TeamPage() { const photos = [alexPhoto, nakashimaPhoto, oleksandrPhoto]; return <><PageLead index="02" kicker="THE TEAM" title="Three perspectives. One delivery standard." intro="NDA is a small distributed team with senior engineering capability, creative technology fluency, and accountable project leadership." /><section className="bg-[#F2F2F2] px-6 pb-20 sm:px-10 sm:pb-28 lg:px-14"><div className="mx-auto max-w-7xl">{TEAM.map((member, i) => <Reveal key={member.name} delay={i * .08}><article className="grid gap-7 border-t border-black/15 py-8 md:grid-cols-[minmax(220px,.85fr)_1.1fr_1fr] md:gap-10 sm:py-12"><div className="aspect-[4/5] overflow-hidden bg-[#F2F2F2]"><img src={photos[i]} alt={member.name} className="h-full w-full object-cover object-top grayscale transition duration-700 hover:scale-105 hover:grayscale-0" loading="lazy" decoding="async" /></div><div className="flex flex-col justify-between"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/45">0{i + 1} / {member.country.toUpperCase()}</p><h2 className="mt-6 text-4xl leading-none tracking-[-.05em] sm:text-5xl">{member.name}</h2><p className="mt-4 font-mono text-xs font-bold uppercase tracking-wide">{member.role}</p></div>{member.link && <a href={member.link} target="_blank" rel="noreferrer" className="mt-8 inline-flex w-fit items-center gap-2 font-mono text-xs font-bold underline underline-offset-4">VIEW PORTFOLIO <MoveUpRight size={14} /></a>}</div><div className="flex flex-col justify-between border-t border-black/15 pt-4 md:border-l md:border-t-0 md:pl-8 md:pt-0"><p className="text-base leading-7 text-black/65">{member.summary}</p><div className="mt-10"><p className="font-mono text-[10px] font-bold tracking-[.15em] text-black/45">FOCUS</p><ul className="mt-4 space-y-2">{member.strengths.map(item => <li key={item} className="flex gap-2 text-sm"><Check size={15} className="mt-0.5 shrink-0" />{item}</li>)}</ul></div></div></article></Reveal>)}</div></section><ContactBand compact /></> }

export function ServicesPage() {
  return <>
    <section className="bg-[#F2F2F2] px-6 pb-16 pt-14 sm:px-10 sm:pb-24 sm:pt-20 lg:px-14">
      <div className="mx-auto max-w-7xl border-t border-black/15 pt-5">
        <div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/50"><span>03</span><span>SERVICES</span></div>
        <div className="mt-12 grid gap-12 lg:grid-cols-[1.3fr_.7fr] lg:items-end lg:gap-20">
          <Reveal><h1 className="max-w-5xl text-[clamp(3.4rem,8.3vw,8rem)] font-medium leading-[.83] tracking-[-.085em]">Make the difficult feel possible.</h1></Reveal>
          <Reveal delay={.1}><div className="max-w-sm lg:pb-2"><p className="text-lg leading-7 text-black/65">Senior engineering and creative technology for teams building something that matters.</p><p className="mt-8 border-l-2 border-black pl-4 font-mono text-[10px] font-bold leading-5 tracking-[.14em] text-black/50">STRATEGY / DESIGN / BUILD / DELIVERY</p></div></Reveal>
        </div>
      </div>
    </section>

    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14">
      <div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[.65fr_1.35fr] md:gap-16 md:items-end"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">OUR CAPABILITY</p><p className="max-w-4xl text-[clamp(2.4rem,5vw,5.2rem)] leading-[.9] tracking-[-.07em]">The right people, close to the work, from first question to final release.</p></div>
    </section>

    <section className="bg-[#F2F2F2] px-6 pb-10 pt-12 sm:px-10 sm:pb-14 sm:pt-16 lg:px-14">
      <div className="mx-auto max-w-7xl">
        <div className="flex items-end justify-between border-b border-black/20 pb-4"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/55">WHAT WE DO</p><h2 className="mt-3 text-3xl tracking-[-.05em] sm:text-5xl">Four ways to move the work forward.</h2></div><span className="hidden font-mono text-[10px] text-black/50 sm:block">04 DISCIPLINES</span></div>
        <div>{services.map((service, i) => <Reveal key={service.title} delay={i * .05}><article className="group grid gap-6 border-b border-black/15 py-8 sm:py-10 md:grid-cols-[52px_minmax(220px,1fr)_minmax(220px,1.1fr)_220px] md:items-center md:gap-8 lg:grid-cols-[64px_minmax(250px,1fr)_minmax(260px,1.1fr)_250px] lg:gap-12"><div className="flex items-start justify-between md:block"><span className="font-mono text-sm font-bold">{service.number}</span><span className="font-mono text-[9px] font-bold tracking-[.14em] text-black/50 md:mt-4 md:block">{service.eyebrow}</span></div><div><h3 className="text-3xl leading-[.9] tracking-[-.06em] sm:text-4xl">{service.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-black/65">{service.body}</p><span className="mt-5 inline-flex items-center gap-2 border-b border-black/60 pb-1 font-mono text-[9px] font-bold tracking-[.12em]">VIEW CAPABILITY <ArrowUpRight size={12} className="transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></span></div><div><p className="max-w-md text-sm leading-6 text-black/60">{service.detail}</p><p className="mt-5 border-l border-black/15 pl-4 font-mono text-[9px] font-bold leading-5 tracking-[.1em] text-black/45 md:mt-6 md:pt-1">{service.stack}</p></div><div className="aspect-[4/3] overflow-hidden bg-black"><picture><source type="image/webp" srcSet={service.webp} /><img src={service.image} alt={`${service.title} visual`} className="h-full w-full object-cover grayscale contrast-125 transition duration-700 group-hover:scale-105 group-hover:grayscale-0" loading="lazy" decoding="async" /></picture></div></article></Reveal>)}</div>
      </div>
    </section>

    <section className="bg-[#F2F2F2] px-6 pb-8 pt-10 sm:px-10 sm:pb-10 sm:pt-14 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/20 pt-4"><div className="grid gap-8 md:grid-cols-[.75fr_1.25fr] md:gap-16"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/55">THE NDA STANDARD</p><h2 className="mt-4 max-w-md text-4xl leading-[.88] tracking-[-.06em] sm:text-6xl">Senior by default.</h2></Reveal><div><Reveal delay={.08}><p className="max-w-3xl text-2xl leading-tight tracking-[-.04em] sm:text-4xl">Clear thinking, visible progress, and a team that stays accountable for the details.</p></Reveal><div className="mt-9 grid border-y border-black/15 sm:grid-cols-3">{[['01', 'Own the outcome'], ['02', 'Keep it clear'], ['03', 'Build for what is next']].map(([no, item], i) => <Reveal key={item} delay={i * .06} className="border-b border-black/15 py-4 last:border-b-0 sm:border-b-0 sm:border-r sm:px-5 sm:first:pl-0 sm:last:border-r-0"><span className="font-mono text-[10px] text-black/45">{no}</span><p className="mt-6 max-w-[150px] text-lg leading-tight tracking-tight">{item}</p></Reveal>)}</div></div></div></div></section>
    <ContactBand compact />
  </>;
}

export function TechnologiesPage() {
  return <>
    <section className="bg-[#F2F2F2] px-6 pb-16 pt-14 sm:px-10 sm:pb-24 sm:pt-20 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/50"><span>04</span><span>TECHNOLOGIES</span></div><div className="mt-12 grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end lg:gap-20"><Reveal><h1 className="max-w-5xl text-[clamp(3.5rem,8.5vw,8.2rem)] font-medium leading-[.82] tracking-[-.085em]">A broad stack, applied with restraint.</h1></Reveal><Reveal delay={.1}><div className="max-w-sm lg:pb-2"><p className="text-lg leading-7 text-black/65">We choose technology for the product in front of us â€” its users, its scale, and the practical life it needs after launch.</p><p className="mt-8 border-l-2 border-black pl-4 font-mono text-[10px] font-bold leading-5 tracking-[.14em] text-black/50">TOOLS ARE A MEANS / NOT THE MESSAGE</p></div></Reveal></div></div></section>
    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[.65fr_1.35fr] md:items-end md:gap-16"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">HOW WE CHOOSE</p><p className="max-w-4xl text-[clamp(2.3rem,4.7vw,4.8rem)] leading-[.9] tracking-[-.065em]">The right technology is the one that makes the product feel <span className="text-white/40">clear, capable, and ready for what comes next.</span></p></div></section>
    <section className="bg-[#F2F2F2] px-6 pb-12 pt-12 sm:px-10 sm:pb-16 sm:pt-16 lg:px-14"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b border-black/15 pb-4"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/55">THE TOOLKIT</p><h2 className="mt-3 text-3xl tracking-[-.05em] sm:text-5xl">Built around the outcome.</h2></div><span className="hidden font-mono text-[10px] text-black/50 sm:block">06 CATEGORIES</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{technologies.map(({ label, items }, i) => { const Icon = technologyIcons[label as keyof typeof technologyIcons]; return <Reveal key={label} delay={i * .05}><article className="group flex h-full min-h-[250px] flex-col bg-black/[.025] p-5 ring-1 ring-black/10 transition-colors duration-300 hover:bg-black hover:text-white sm:p-6"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center bg-black text-white transition-colors duration-300 group-hover:bg-white group-hover:text-black"><Icon size={19} strokeWidth={1.5} /></span><span className="font-mono text-[10px] text-black/45 transition-colors group-hover:text-white/50">{String(i + 1).padStart(2, '0')}</span></div><div className="mt-auto"><h3 className="text-3xl leading-none tracking-[-.055em]">{label}</h3><div className="mt-6 grid grid-cols-2 gap-x-5 gap-y-2 sm:grid-cols-3">{items.map(item => <span key={item} className="font-mono text-xs text-black/60 transition-colors group-hover:text-white/65">{item}</span>)}</div></div></article></Reveal>; })}</div></div></section>
    <section className="bg-[#F2F2F2] px-6 pb-10 pt-2 sm:px-10 sm:pb-14 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/20 pt-10 sm:pt-14"><div className="grid gap-8 md:grid-cols-[.65fr_1.35fr] md:gap-16"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/55">THE PRINCIPLE</p></Reveal><Reveal delay={.08}><p className="max-w-5xl text-3xl leading-[.94] tracking-[-.06em] sm:text-6xl">The stack should disappear behind a product that feels fast, clear, and dependable.</p></Reveal></div></div></section>
    <ContactBand compact />
  </>;
}

export function ProcessPage() {
  return <>
    <section className="bg-[#F2F2F2] px-6 pb-16 pt-14 sm:px-10 sm:pb-24 sm:pt-20 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/50"><span>05</span><span>PROCESS</span></div><div className="mt-12 grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:gap-20"><Reveal><h1 className="max-w-5xl text-[clamp(3.5rem,8.4vw,8.2rem)] font-medium leading-[.82] tracking-[-.085em]">A clear route from question to release.</h1></Reveal><Reveal delay={.1}><div className="max-w-sm lg:pb-2"><p className="text-lg leading-7 text-black/65">Structured enough to protect the work. Flexible enough to respond to what we learn together.</p><p className="mt-8 border-l-2 border-black pl-4 font-mono text-[10px] font-bold leading-5 tracking-[.14em] text-black/50">FRAME / PLAN / BUILD / SHIP / EVOLVE</p></div></Reveal></div></div></section>
    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[.65fr_1.35fr] md:items-end md:gap-16"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">THE ROUTE</p><p className="max-w-4xl text-[clamp(2.3rem,4.7vw,4.8rem)] leading-[.9] tracking-[-.065em]">Good work gets clearer as it moves. Every stage has a purpose, a decision, and a next step.</p></div></section>
    <section className="bg-black px-6 pb-14 text-white sm:px-10 sm:pb-24 lg:px-14"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between border-b border-white/15 pb-4"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">FIVE STAGES</p><span className="font-mono text-[10px] text-white/40">NDA / DELIVERY MODEL</span></div><div className="relative">{process.map(([number, title, body], i) => <Reveal key={number} delay={i * .06}><article className="group grid gap-6 border-b border-white/15 py-8 sm:py-10 md:grid-cols-[72px_1fr_1fr_20px] md:items-start md:gap-10 lg:grid-cols-[92px_1fr_1fr_20px] lg:gap-16"><div><span className="font-mono text-3xl font-bold tracking-[-.08em] text-white/35 transition-colors duration-300 group-hover:text-white">{number}</span><span className="mt-5 hidden h-px w-8 bg-white/30 transition-all duration-300 group-hover:w-14 md:block" /></div><h2 className="max-w-lg text-3xl leading-[.9] tracking-[-.055em] sm:text-5xl">{title}</h2><p className="max-w-md text-sm leading-6 text-white/60">{body}</p><span className="mt-1 hidden h-3 w-3 rounded-full border border-white/45 transition-colors duration-300 group-hover:bg-white md:block" /></article></Reveal>)}</div></div></section>
    <section className="bg-[#F2F2F2] px-6 pb-10 pt-12 sm:px-10 sm:pb-14 sm:pt-16 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="grid gap-8 md:grid-cols-[.65fr_1.35fr] md:gap-16"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/50">WHAT STAYS CONSTANT</p></Reveal><Reveal delay={.08}><p className="max-w-4xl text-3xl leading-[.94] tracking-[-.06em] sm:text-6xl">Clarity in the plan. Care in the craft. Confidence in the release.</p></Reveal></div></div></section>
    <ContactBand compact />
  </>;
}

export function ProjectsPage({ onNavigate }: { onNavigate: () => void }) { return <><PageLead index="06" kicker="SELECTED WORK" title="Digital work across play, finance, and connection." intro="A selection of projects spanning mobile games, fintech products, commerce, real-time platforms, and web3 experiences." /><section className="bg-[#F2F2F2] px-6 pb-20 sm:px-10 sm:pb-28 lg:px-14"><div className="mx-auto grid max-w-7xl gap-x-8 gap-y-16 md:grid-cols-2">{projects.map((project, i) => <Reveal key={project.title} delay={(i % 2) * .07}><article className={i % 3 === 0 ? 'md:pt-16' : ''}><div className="group relative aspect-[16/10] overflow-hidden bg-[#F2F2F2]"><img src={project.image} alt={project.title} className="h-full w-full object-cover transition duration-700 ease-out group-hover:scale-105" loading="lazy" decoding="async" /><div className="absolute inset-0 bg-black/0 transition-colors duration-500 group-hover:bg-black/10" /><span className="absolute bottom-4 right-4 flex h-10 w-10 translate-y-2 items-center justify-center bg-white opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100"><ArrowUpRight size={18} /></span></div><div className="mt-5 flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-black/45">{project.category.toUpperCase()}</p><h2 className="mt-2 text-3xl tracking-[-.045em]">{project.title}</h2><p className="mt-3 max-w-md text-sm leading-6 text-black/60">{project.text}</p></div><span className="font-mono text-[10px] text-black/40">{String(i + 1).padStart(2, '0')}</span></div><div className="mt-4 flex gap-2">{project.stack.map(item => <span key={item} className="border border-black/15 px-2 py-1 font-mono text-[10px]">{item}</span>)}</div></article></Reveal>)}</div><div className="mt-20 border-t border-black/15 pt-6"><button onClick={onNavigate} className="group inline-flex items-center gap-3 font-mono text-xs font-bold tracking-wide">HAVE A PROJECT IN MIND <ArrowUpRight size={16} className="transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></button></div></section><ContactBand compact /></> }

export function TestimonialsPage() { return <><PageLead index="07" kicker="TESTIMONIALS" title="Trust is earned in the work." intro="We value direct, private client relationships. References and relevant delivery context can be shared in a conversation where appropriate." /><section className="bg-black px-6 py-20 text-white sm:px-10 sm:py-28 lg:px-14"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[.7fr_1.3fr]"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">OUR APPROACH</p></Reveal><Reveal delay={.08}><p className="text-4xl leading-[.98] tracking-[-.045em] sm:text-6xl">No invented quotes. No anonymous superlatives. Just a team that takes delivery seriously.</p><p className="mt-8 max-w-xl text-base leading-7 text-white/60">The best evidence is clear communication, reliable work, and relationships that continue beyond a single release.</p></Reveal></div></section><ContactBand /></> }


