import { motion } from 'motion/react';
import { ArrowUpRight } from 'lucide-react';

const services = [
  { no: '01', title: 'Product engineering', lead: 'Web products that feel considered from the first interaction to the last edge case.', body: 'Full-stack application development, frontend systems, backend architecture, and the practical foundations needed to keep a product dependable.', tags: 'React · Next.js · TypeScript · Node.js' },
  { no: '02', title: 'Interactive development', lead: 'Experiences with motion, depth, and a clear reason for being there.', body: 'WebGL, Three.js, Unity, and real-time interaction shaped around the story the product needs to tell.', tags: 'WebGL · Three.js · Unity · C#' },
  { no: '03', title: 'Blockchain systems', lead: 'Decentralized technology applied with clarity and restraint.', body: 'Web3 products, smart-contract integrations, wallet flows, and interfaces that make complex systems feel approachable.', tags: 'Solidity · Web3 · React · Node.js' },
  { no: '04', title: 'Cloud & delivery', lead: 'The infrastructure behind a release you can trust.', body: 'Cloud architecture, deployment workflows, performance work, and operational care that keep teams moving after launch.', tags: 'AWS · Azure · Docker · Firebase' },
];

const principles = ['Senior hands stay close to the work.', 'Scope remains visible and practical.', 'Quality is part of every stage.', 'The right technology serves the outcome.'];
const Reveal = ({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) => <motion.div className={className} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ duration: .65, delay, ease: [0.16, 1, 0.3, 1] }}>{children}</motion.div>;

export function ServicesPage() {
  return <>
    <section className="bg-[#F2F2F2] px-6 pb-12 pt-14 sm:px-10 sm:pb-16 sm:pt-20 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/50"><span>03</span><span>SERVICES</span></div><div className="mt-10 grid gap-8 md:grid-cols-[1.25fr_.75fr] md:items-end md:gap-16"><Reveal><h1 className="max-w-5xl text-[clamp(3rem,6.7vw,6.7rem)] font-medium leading-[.86] tracking-[-.075em]">Capability to make a product real.</h1></Reveal><Reveal delay={.1}><p className="max-w-sm text-base leading-7 text-black/65">NDA brings the right senior expertise to the problem in front of you—without unnecessary layers or one-size-fits-all packages.</p></Reveal></div></div></section>

    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto grid max-w-7xl gap-7 md:grid-cols-[.7fr_1.3fr] md:gap-16"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">HOW WE HELP</p><p className="max-w-4xl text-[clamp(2rem,4vw,4rem)] leading-[.96] tracking-[-.06em]">From a difficult first question to a product that is ready for <span className="text-white/45">real people.</span></p></div></section>

    <section className="bg-[#F2F2F2] px-6 py-4 sm:px-10 sm:py-8 lg:px-14"><div className="mx-auto max-w-7xl">{services.map((service, i) => <Reveal key={service.title} delay={i * .06}><article className="grid gap-7 border-t border-black/15 py-10 sm:py-14 md:grid-cols-[70px_1fr_1fr] md:gap-10 lg:gap-16"><div className="font-mono text-xs text-black/40">{service.no}</div><div><h2 className="max-w-md text-4xl leading-[.9] tracking-[-.06em] sm:text-5xl">{service.title}</h2><p className="mt-5 max-w-md text-lg leading-7 tracking-[-.02em] text-black/75">{service.lead}</p></div><div className="border-t border-black/10 pt-5 md:border-t-0 md:pt-1"><p className="max-w-md text-sm leading-6 text-black/60">{service.body}</p><p className="mt-7 font-mono text-[10px] font-bold leading-5 tracking-[.1em] text-black/45">{service.tags}</p></div></article></Reveal>)}</div></section>

    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[.7fr_1.3fr] md:gap-16"><Reveal><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">THE NDA STANDARD</p></Reveal><div className="grid gap-0 sm:grid-cols-2">{principles.map((principle, i) => <Reveal key={principle} delay={i * .06} className="border-t border-white/20 py-5 sm:mr-8"><div className="flex gap-5"><span className="font-mono text-[10px] text-white/40">0{i + 1}</span><p className="max-w-xs text-xl leading-tight tracking-[-.03em]">{principle}</p></div></Reveal>)}</div></div></section>

    <section className="bg-[#F2F2F2] px-6 pb-14 pt-2 sm:px-10 sm:pb-20 lg:px-14"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 border-t border-black/15 pt-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/50">START WITH THE PROBLEM</p><h2 className="mt-4 max-w-xl text-4xl leading-[.95] tracking-[-.05em] sm:text-5xl">Tell us what needs to become clearer.</h2></div><a href="mailto:saasbusiness2026@gmail.com" className="group inline-flex w-fit items-center gap-3 bg-black px-5 py-4 font-mono text-xs font-bold tracking-wide text-white transition-transform hover:-translate-y-1">EMAIL NDA <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></a></div></section>
  </>;
}
