import { motion } from 'motion/react';
import { ArrowUpRight } from 'lucide-react';
import { TEAM } from '../site';
import alexPhoto from '../../project images/Alex.jpg';
import nakashimaPhoto from '../../project images/Nakashima.jpg';
import oleksandrPhoto from '../../project images/Oleksandr.jpg';

const photos = [alexPhoto, nakashimaPhoto, oleksandrPhoto];
const profileDetails = [
  { summary: 'Senior engineer focused on reliable, end-to-end software products and cloud-ready delivery.', focus: 'Full-stack architecture · Product delivery · Cloud & DevOps' },
  { summary: 'Senior developer shaping engaging web, blockchain, and Unity experiences with dependable technical foundations.', focus: 'Interactive products · Blockchain systems · Game development' },
  { summary: 'Team manager responsible for project planning, client communication, team coordination, and a calm path to delivery.', focus: 'Project planning · Agile workflow · Client communication · Team leadership' },
];
const Reveal = ({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) => <motion.div className={className} initial={{ opacity: 0, y: 24, filter: 'blur(5px)' }} whileInView={{ opacity: 1, y: 0, filter: 'blur(0px)' }} viewport={{ once: true, margin: '0px 0px -60px 0px', amount: .1 }} transition={{ duration: .8, delay, ease: [0.16, 1, 0.3, 1] }}>{children}</motion.div>;

export function TeamPage() {
  return <>
    <section className="bg-[#F2F2F2] px-6 pb-12 pt-14 sm:px-10 sm:pb-16 sm:pt-20 lg:px-14"><div className="mx-auto max-w-7xl border-t border-black/15 pt-5"><div className="flex items-center justify-between font-mono text-[10px] font-bold tracking-[.16em] text-black/50"><span>02</span><span>THE TEAM</span></div><div className="mt-10 grid gap-8 md:grid-cols-[1.2fr_.8fr] md:items-end md:gap-16"><Reveal><h1 className="max-w-4xl text-[clamp(3rem,6.6vw,6.6rem)] font-medium leading-[.87] tracking-[-.075em]">The people behind the work.</h1></Reveal><Reveal delay={.1}><p className="max-w-sm text-base leading-7 text-black/65">Three senior perspectives, one direct line from the first conversation to the finished product.</p></Reveal></div></div></section>

    <section className="bg-black px-6 py-12 text-white sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto grid max-w-7xl gap-7 md:grid-cols-[.7fr_1.3fr] md:gap-16"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-white/45">NDA / 03 PEOPLE</p><p className="max-w-4xl text-[clamp(2rem,4vw,4rem)] leading-[.96] tracking-[-.06em]">A small team keeps decisions <span className="text-white/45">clear</span> and accountability close.</p></div></section>

    <section className="bg-[#F2F2F2] px-6 py-12 sm:px-10 sm:py-16 lg:px-14"><div className="mx-auto max-w-7xl"><div className="mb-5 hidden grid-cols-[70px_210px_1fr_190px] gap-8 pb-4 font-mono text-[10px] font-bold tracking-[.14em] text-black/40 lg:grid"><span>NO.</span><span>PORTRAIT</span><span>PERSON</span><span>CORE FOCUS</span></div>{TEAM.map((member, i) => <Reveal key={member.name} delay={i * .07}><article className="grid gap-6 border-t border-black/15 py-7 sm:py-9 lg:grid-cols-[70px_210px_1fr_270px] lg:items-center lg:gap-8"><div className="hidden font-mono text-xs text-black/40 lg:block">0{i + 1}</div><div className="relative aspect-[4/3] overflow-hidden bg-[#F2F2F2] sm:aspect-[16/8] lg:aspect-[4/5]"><img src={photos[i]} alt={member.name} className="h-full w-full object-cover object-top grayscale transition duration-700 hover:scale-[1.04] hover:grayscale-0" loading="lazy" decoding="async" /><span className="absolute left-3 top-3 bg-black px-2 py-1 font-mono text-[10px] text-white lg:hidden">0{i + 1}</span></div><div className="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-start lg:block"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-black/45">{member.country.toUpperCase()}</p><h2 className="mt-3 max-w-lg text-3xl leading-[.94] tracking-[-.055em] sm:text-4xl">{member.name}</h2><p className="mt-3 max-w-xs font-mono text-[10px] font-bold uppercase leading-5 tracking-[.08em]">{member.role}</p></div>{member.link && <a href={member.link} target="_blank" rel="noreferrer" className="group mt-1 inline-flex h-9 w-9 items-center justify-center border border-black/20 transition-colors hover:bg-black hover:text-white sm:mt-0 lg:mt-7" aria-label={`View ${member.name} portfolio`}><ArrowUpRight size={15} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a>}</div><div className="border-t border-black/10 pt-5 lg:border-t-0 lg:pt-0"><p className="text-sm leading-6 text-black/65">{profileDetails[i].summary}</p><p className="mt-4 font-mono text-[10px] font-bold leading-5 tracking-[.1em] text-black/45">{profileDetails[i].focus}</p></div></article></Reveal>)}</div></section>

    <section className="bg-[#F2F2F2] px-6 pb-14 pt-2 sm:px-10 sm:pb-20 lg:px-14"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 border-t border-black/15 pt-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold tracking-[.16em] text-black/50">WORK WITH NDA</p><h2 className="mt-4 max-w-xl text-4xl leading-[.95] tracking-[-.05em] sm:text-5xl">The right conversation starts with the right people.</h2></div><a href="mailto:saasbusiness2026@gmail.com" className="group inline-flex w-fit items-center gap-3 bg-black px-5 py-4 font-mono text-xs font-bold tracking-wide text-white transition-transform hover:-translate-y-1">EMAIL NDA <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></a></div></section>
  </>;
}
